version: '3.3'
services:
  db:
    build: ./docker/mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3314:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  quiz:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    tty: true
    ports:
      - "8000:8000"
