version: '3.3'
services:
  db:
    build: ./mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/config/conf.d:/etc/mysql/conf.d
      - ./volume/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./volume/mysql/log:/var/log/mysql
  quiz:
    build: ./quiz
    depends_on:
      - db
    volumes:
      - ./quiz:/code
    tty: true
    ports:
      - "8000:8000"
