# Generated by Django 2.1 on 2019-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=28, primary_key=True, serialize=False),
        ),
    ]
