# Generated by Django 2.1 on 2019-11-03 13:33

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191020_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='degree',
            field=models.IntegerField(default=1, validators=[rest_framework.compat.MinValueValidator(1), rest_framework.compat.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
