# Generated by Django 2.1 on 2019-06-08 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_cd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_cd', models.CharField(max_length=6)),
                ('answer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_cd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_nm', models.CharField(max_length=60)),
                ('is_deleted', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_cd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('q_details', models.CharField(max_length=255)),
                ('sort_cd', models.CharField(max_length=6)),
                ('is_deleted', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_cd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_nm', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('authority_cd', models.CharField(max_length=5)),
                ('is_deleted', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Group')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.User'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
    ]
