# Generated by Django 2.1 on 2019-05-16 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_cd', models.CharField(max_length=6)),
                ('question_cd', models.CharField(max_length=6)),
                ('answer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_cd', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('group_nm', models.CharField(max_length=60)),
                ('use_flg', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('group_cd', models.CharField(max_length=2)),
                ('question', models.CharField(max_length=255)),
                ('q_details', models.CharField(max_length=255)),
                ('q_details_1', models.CharField(max_length=60)),
                ('q_details_2', models.CharField(max_length=60)),
                ('q_details_3', models.CharField(max_length=60)),
                ('q_details_4', models.CharField(max_length=60)),
                ('q_details_5', models.CharField(max_length=60)),
                ('sort_cd', models.CharField(max_length=6)),
                ('use_flg', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('group_cd', models.CharField(max_length=2)),
                ('user_id', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_nm', models.CharField(max_length=60)),
                ('mailto', models.CharField(max_length=60)),
                ('authority_cd', models.CharField(max_length=5)),
                ('use_flg', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user_cd', 'question_cd')},
        ),
    ]
